import type { NextPage } from "next";
import { useEffect, useState } from "react";
import { useAccount, Chain, useNetwork, useContract } from "wagmi";

import { useDispatch, useSelector } from "react-redux";
import {
  fetchNumberTransactions,
  fetchBalance,
  getGasPrice,
  getAllToken,
} from "../actions/transactionsActions";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import TableTransaction from "./TableTransaction";
import TableAsset from "./TableAssets";

const Home: NextPage = () => {
  const { address, isConnecting, isDisconnected } = useAccount();
  const { chain } = useNetwork();

  const dispatch = useDispatch();

  const [NumberTransactions, setTransactions] = useState<Number | undefined>(0);
  const [transactionsList, setListTransactions] = useState<any | undefined>([]);
  const [balance, setbalance] = useState(0);
  const [gas, setGas] = useState(0);
  const [tokens, setAllToken] = useState<any | undefined>([]);

  const transactionsCount = useSelector(
    (state: { transactions: { count: any } }) => state.transactions.count
  );
  const balanceWallet = useSelector(
    (state: { balance: { count: any } }) => state.balance.count
  );
  const transactionHistory = useSelector(
    (state: { transactions: { transactionHistory: any } }) =>
      state.transactions.transactionHistory
  );
  const gasPrice = useSelector(
    (state: { blockchain: { gasPrice: any } }) => state.blockchain.gasPrice
  );
  const allToken = useSelector(
    (state: { balance: { tokens: any } }) => state.balance.tokens
  );

  useEffect(() => {
    if (address) {
      dispatch(fetchNumberTransactions(address));
      dispatch(fetchBalance(address));
      dispatch(getGasPrice());
      dispatch(getAllToken(address));
    }
  }, [address]);

  useEffect(() => {
    setTransactions(transactionsCount);
    setListTransactions(transactionHistory);
    setbalance(balanceWallet);
    setGas(gasPrice);
    setAllToken(allToken);
  }, [
    transactionsCount,
    transactionHistory,
    balanceWallet,
    gasPrice,
    allToken,
  ]);

  console.log(tokens);
  return (
    <div className="p-4 sm:ml-64 bg-slate-100">
      <div className={styles.container}>
        <Head>
          <title>RainbowKit App</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <main className={styles.main}>
          <div className="container mx-auto mb-8 flex justify-around">
            <article className="flex items-end justify-between rounded-lg border border-gray-100 bg-white p-6">
              <div>
                <p className="text-sm text-gray-500">Profit</p>
                <p className="text-2xl font-medium text-gray-900">
                  {balance} ETH
                </p>
              </div>
              <div className="ml-5 inline-flex gap-2 rounded bg-green-100 p-1 text-green-600">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"
                  />
                </svg>
                <span className="text-xs font-medium"> 67.81% </span>
              </div>
            </article>
            <article className="flex items-end justify-between rounded-lg border border-gray-100 bg-white p-6">
              <div>
                <p className="text-sm text-gray-500">Gas Price</p>
                <p className="text-2xl font-medium text-gray-900">{gas} WEI</p>
              </div>
              <div className="ml-5 inline-flex gap-2 rounded bg-green-100 p-1 text-green-600">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"
                  />
                </svg>
                <span className="text-xs font-medium"> 67.81% </span>
              </div>
            </article>
          </div>
          <TableAsset assetList={tokens} />
          <TableTransaction transactionsList={transactionsList} />
        </main>

        <footer className={styles.footer}>
          <a
            href="https://rainbow.me"
            rel="noopener noreferrer"
            target="_blank"
          >
            Made with ❤️ by your frens at 🌈
          </a>
        </footer>
      </div>
    </div>
  );
};

export default Home;
// https://etherscan.io/tx/
